import React from 'react'
import { useState,useEffect } from 'react'
import {Loader,Card, FormFiled} from "../components"

const RenderCard = ({data,title}) =>{
   if(data?.length > 0){
    return data.map((post) => <Card  key={post._id} {...post}/>)
   }
   return (
    <h2 className='mt-5 text-bold text-blue-600 text-xl-uppercase'>{title}</h2>
   )
}


const Home = () => {
  const[loading, setLoading] = useState(false)
  const[allposts,setallposts] = useState(null)
  const[searchText, setsearchText] = useState("andgdfg")
  return ( 
      <section className='max-w-7xl mx-auto'>
  <div>
    <h1 className='font-extrabold text-black-700 text-4xl'>The Comminity showcase</h1>
    <p className='mt-4 text-1xl  text-gray-500'>Browse though a collection of imaginative and visually stunning images generated by AI</p>
  </div>

  <div className='mt-20'>
    <FormFiled />
  </div>

  <div className='mt-10'>
    {loading ? ( 
      <div className='flex justify-center items-center'>
        <Loader />
        </div >
      ) : (<> 
      {searchText && (
        <h2 className='mt-3 text-xl font-medium text-gray-600'>showing results for:- 
        <span className='text-black'>{searchText}</span></h2>
      )}
       {/* // when there are losts of images to handle use grid */}
      <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
           {searchText ? (
            <RenderCard  
            data={[]}
            title="no result found" />
           ) : (
            <RenderCard 
            data={[]}
            title="no post found" />
           )}
      </div>
      
       </>)}
  </div>
      </section>

  )
}

export default Home